version: "3.8"
services:
  otter:
    image: registry.cn-hangzhou.aliyuncs.com/redgreat/otter
    restart: unless-stopped
    container_name: otter
    hostname: otter
    ports:
      - "8080:8080"   # Manager Web 界面
      - "8018:8018"   # ZooKeeper Admin
      - "2181:2181"   # ZooKeeper 客户端
      - "2088:2088"   # Node 服务端口
      - "2089:2089"   # Node 下载端口
      - "2090:2090"   # Node MBean 端口
    environment:
      TZ: Asia/Shanghai
      RUN_MODE: ALL
      MANAGER_ADD: otter
      OTTER_MANAGER_MYSQL: "fn.wongcw.cn:3306"
      MYSQL_USER: "otter"
      MYSQL_PASSWORD: "Lunz2017"
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536